[project]
name = "mcp-python-weather"
version = "0.1.0"
description = "Python Weather MCP"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "mcp[cli]>=1.9.4",
    "requests>=2.32.4",
    "torch>=2.9.0",
    "transformers>=4.57.1",
]
